s=set()
# print(type(s))
# s_from_list=set([1,2,4,7])
# print(s_from_list)
# print(type(s_from_list))
l=[1,3,4,6]
s_from_list=set(l)
print(s_from_list)
s_from_list.add(9)
print(s_from_list)
s_from_list.remove(3)
print(s_from_list)
s_from_list.discard(6)
print(s_from_list)
